version: "3"

volumes:
  rabbitmq_data:

services:
 
  ###################################
  # Room: The Room simple microservice
  ###################################
  room:
    build:
      context: ./simple
      dockerfile: room.Dockerfile
    image: aarontanyien/room:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/room
      PYTHONUNBUFFERED: 1

  ###################################
  # Game: The Game simple microservice
  ###################################
  game:
    build:
      context: ./simple
      dockerfile: game.Dockerfile
    image: aarontanyien/game:1.0
    restart: always
    environment:
      PYTHONUNBUFFERED: 1

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: playfoo-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
      
  #################################################
  # Activity Log: The Activity Log simple microservice
  #################################################
  activity_log:
    build:
      context: ./simple
      dockerfile: activity_log.Dockerfile
    image: aarontanyien/activity_log:1.0
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/activity_log

  ###################################
  # Error: The Error simple microservice
  ###################################
  error:
    build:
      context: ./simple
      dockerfile: error.Dockerfile
    image: aarontanyien/error:1.0
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/error
  
  ##################################
  # Message: The Message simple microservice
  ##################################
  message:
    build:
      context: ./simple
      dockerfile: message.Dockerfile
    image: aarontanyien/message:1.0
    restart: always
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/message
      PYTHONUNBUFFERED: 1

  ##################################
  # Message_Listener: The Message Listener simple microservice
  ##################################
  message_lister:
    build:
      context: ./simple
      dockerfile: message_listener.Dockerfile
    image: aarontanyien/message_listener:1.0
    restart: always
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/message
      PYTHONUNBUFFERED: 1
      ports:
      - "5003:5003"

  ###############################################
  # Create Room: The Create Room complex microservice
  ###############################################
  Create_Room:
    build:
      context: ./complex
      dockerfile: Create_Room.Dockerfile
    image: aarontanyien/create_room:1.0
    restart: always
    depends_on:
      - room
      - game
      - activity_log
      - error
      - message
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      user_URL: http://user:5000/user
      room_URL: http://room:5001/room
      game_URL: http://game:5002/game
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"

  ###############################################
  # Join Room: The Join Room complex microservice
  ###############################################
  Join_Room:
    build:
      context: ./complex
      dockerfile: Join_Room.Dockerfile
    image: aarontanyien/join_room:1.0
    restart: always
    depends_on:
      - room
      - game
      - activity_log
      - error
      - message
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      user_URL: http://user:5000/user
      room_URL: http://room:5001/room
      game_URL: http://game:5002/game
      PYTHONUNBUFFERED: 1
    ports:
      - "5101:5101"

  ###############################################
  # Leave Room: The Leave Room complex microservice
  ###############################################
  Leave_Room:
    build:
      context: ./complex
      dockerfile: Leave_Room.Dockerfile
    image: aarontanyien/leave_room:1.0
    restart: always
    depends_on:
      - room
      - activity_log
      - error
      - message
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      user_URL: http://user:5000/user
      room_URL: http://room:5001/room
      PYTHONUNBUFFERED: 1
    ports:
      - "5102:5102"

  ###############################################
  # Send Message: The Send Message complex microservice
  ###############################################
  Send_Message:
    build:
      context: ./complex
      dockerfile: Send_Message.Dockerfile
    image: aarontanyien/send_message:1.0
    restart: always
    depends_on:
      - room
      - activity_log
      - error
      - message
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      user_URL: http://user:5000/user
      room_URL: http://room:5001/room 
      PYTHONUNBUFFERED: 1
    ports:
      - "5103:5103"
