apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
        -o kubemanifests.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: create-room
    name: create-room
  spec:
    ports:
    - name: "5100"
      port: 5100
      targetPort: 5100
    selector:
      io.kompose.service: create-room
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
        -o kubemanifests.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: join-room
    name: join-room
  spec:
    ports:
    - name: "5101"
      port: 5101
      targetPort: 5101
    selector:
      io.kompose.service: join-room
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
        -o kubemanifests.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: leave-room
    name: leave-room
  spec:
    ports:
    - name: "5102"
      port: 5102
      targetPort: 5102
    selector:
      io.kompose.service: leave-room
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
        -o kubemanifests.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: rabbitmq
    name: rabbitmq
  spec:
    ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "15672"
      port: 15672
      targetPort: 15672
    selector:
      io.kompose.service: rabbitmq
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
        -o kubemanifests.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: send-message
    name: send-message
  spec:
    ports:
    - name: "5103"
      port: 5103
      targetPort: 5103
    selector:
      io.kompose.service: send-message
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
        -o kubemanifests.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: activity-log
    name: activity-log
  spec:
    replicas: 2
    selector:
      matchLabels:
        io.kompose.service: activity-log
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
            -o kubemanifests.yaml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: activity-log
      spec:
        containers:
        - env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: dbURL
            value: mysql+mysqlconnector://is213@host.docker.internal:3306/activity_log
          - name: rabbit_host
            value: rabbitmq
          - name: rabbit_port
            value: "5672"
          image: aarontanyien/activity_log:1.0
          imagePullPolicy: Never
          name: activity-log
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
        -o kubemanifests.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: create-room
    name: create-room
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: create-room
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
            -o kubemanifests.yaml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: create-room
      spec:
        containers:
        - env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: game_URL
            value: http://game:5002/game
          - name: rabbit_host
            value: rabbitmq
          - name: rabbit_port
            value: "5672"
          - name: room_URL
            value: http://room:5001/room
          - name: user_URL
            value: http://user:5000/user
          image: aarontanyien/create_room:1.0
          imagePullPolicy: Never
          name: create-room
          ports:
          - containerPort: 5100
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
        -o kubemanifests.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: error
    name: error
  spec:
    replicas: 2
    selector:
      matchLabels:
        io.kompose.service: error
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
            -o kubemanifests.yaml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: error
      spec:
        containers:
        - env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: dbURL
            value: mysql+mysqlconnector://is213@host.docker.internal:3306/error
          - name: rabbit_host
            value: rabbitmq
          - name: rabbit_port
            value: "5672"
          image: aarontanyien/error:1.0
          imagePullPolicy: Never
          name: error
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
        -o kubemanifests.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: game
    name: game
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: game
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
            -o kubemanifests.yaml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: game
      spec:
        containers:
        - env:
          - name: PYTHONUNBUFFERED
            value: "1"
          image: aarontanyien/game:1.0
          imagePullPolicy: Never
          name: game
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
        -o kubemanifests.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: join-room
    name: join-room
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: join-room
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
            -o kubemanifests.yaml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: join-room
      spec:
        containers:
        - env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: game_URL
            value: http://game:5002/game
          - name: rabbit_host
            value: rabbitmq
          - name: rabbit_port
            value: "5672"
          - name: room_URL
            value: http://room:5001/room
          - name: user_URL
            value: http://user:5000/user
          image: aarontanyien/join_room:1.0
          imagePullPolicy: Never
          name: join-room
          ports:
          - containerPort: 5101
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
        -o kubemanifests.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: leave-room
    name: leave-room
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: leave-room
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
            -o kubemanifests.yaml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: leave-room
      spec:
        containers:
        - env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: rabbit_host
            value: rabbitmq
          - name: rabbit_port
            value: "5672"
          - name: room_URL
            value: http://room:5001/room
          - name: user_URL
            value: http://user:5000/user
          image: aarontanyien/leave_room:1.0
          imagePullPolicy: Never
          name: leave-room
          ports:
          - containerPort: 5102
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
        -o kubemanifests.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: message
    name: message
  spec:
    replicas: 3
    selector:
      matchLabels:
        io.kompose.service: message
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
            -o kubemanifests.yaml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: message
      spec:
        containers:
        - env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: dbURL
            value: mysql+mysqlconnector://is213@host.docker.internal:3306/message
          - name: rabbit_host
            value: rabbitmq
          - name: rabbit_port
            value: "5672"
          image: aarontanyien/message:1.0
          imagePullPolicy: Never
          name: message
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
        -o kubemanifests.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: message-lister
    name: message-lister
  spec:
    replicas: 4
    selector:
      matchLabels:
        io.kompose.service: message-lister
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
            -o kubemanifests.yaml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: message-lister
      spec:
        containers:
        - env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: dbURL
            value: mysql+mysqlconnector://is213@host.docker.internal:3306/message
          - name: rabbit_host
            value: rabbitmq
          - name: rabbit_port
            value: "5672"
          image: aarontanyien/message_listener:1.0
          imagePullPolicy: Never
          name: message-lister
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
        -o kubemanifests.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: rabbitmq
    name: rabbitmq
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: rabbitmq
    strategy:
      type: Recreate
    template:
      metadata:
        annotations:
          kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
            -o kubemanifests.yaml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: rabbitmq
      spec:
        containers:
        - image: rabbitmq:3-management
          imagePullPolicy: ""
          name: rabbitmq
          ports:
          - containerPort: 5672
          - containerPort: 15672
          resources: {}
          volumeMounts:
          - mountPath: /var/lib/rabbitmq
            name: rabbitmq-data
        hostname: playfoo-rabbit
        restartPolicy: Always
        serviceAccountName: ""
        volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-data
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: rabbitmq-data
    name: rabbitmq-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
        -o kubemanifests.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: room
    name: room
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: room
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
            -o kubemanifests.yaml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: room
      spec:
        containers:
        - env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: dbURL
            value: mysql+mysqlconnector://is213@host.docker.internal:3306/room
          image: aarontanyien/room:1.0
          imagePullPolicy: Never
          name: room
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
        -o kubemanifests.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: send-message
    name: send-message
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: send-message
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: D:\Programming Tools\Kompose\kompose.exe convert -f docker-compose.yml
            -o kubemanifests.yaml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: send-message
      spec:
        containers:
        - env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: rabbit_host
            value: rabbitmq
          - name: rabbit_port
            value: "5672"
          - name: room_URL
            value: http://room:5001/room
          - name: user_URL
            value: http://user:5000/user
          image: aarontanyien/send_message:1.0
          imagePullPolicy: Never
          name: send-message
          ports:
          - containerPort: 5103
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
kind: List
metadata: {}

